//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelleEssense.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotion
    {
        public int LotionId { get; set; }
        public int TypeId { get; set; }
        public int LabelId { get; set; }
        public int ScentId { get; set; }
        public int SizeId { get; set; }
        public decimal Price { get; set; }
        public float Discount { get; set; }
        public bool AddCBD { get; set; }
        public bool AddMagOil { get; set; }
        public bool IsFeatured { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string Photo5 { get; set; }
        public string Notes { get; set; }
    
        public virtual Label Label { get; set; }
        public virtual Product Product { get; set; }
        public virtual Scent Scent { get; set; }
        public virtual Size Size { get; set; }
    }
}
